from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^$', 'app.views.home'),
    url(r'^autentificacion$', 'app.views.autentificacion'),
    url(r'^autentificacion/$', 'app.views.autentificacion'),
    url(r'^productos/$', 'app.views.productos'),
    url(r'^ingresar/(\w+)$', 'app.views.ingresar'),
    url(r'^ingresar/(\w+)/$', 'app.views.ingresar'),
    url(r'^ingresar/$', 'app.views.ingresarone'),
    url(r'^registra/$', 'app.views.registra'),
    url(r'^salir/$', 'app.views.salir'),
    url(r'^provincias$', 'app.views.provincias'),
    url(r'^perfil/$', 'app.views.perfil'),
    url(r'^vender/$', 'app.views.vender'),
    url(r'^productos/(\d+)$', 'app.views.productos'),
    url(r'^productosamostrar/(\d+)$', 'app.views.productosamostrar'),
    url(r'^producto/(\d+)$', 'app.views.producto'),
    url(r'^productojson/(\d+)$', 'app.views.productojson'),
    url(r'^usuario/(\d+)$', 'app.views.usuario'),
    url(r'^editarproducto/(\d+)$', 'app.views.editarproducto'),
    url(r'^chat/(\d+)/(\d+)$', 'app.views.chat'),
    url(r'^chatin/(\d+)$', 'app.views.chatin'),
    url(r'^chatin2/(\d+)$', 'app.views.chatin2'),
    url(r'^enviamensaje/$', 'app.views.enviamensaje'),
    url(r'^enviamensaje_perfil/$', 'app.views.enviamensaje_perfil'),
    url(r'^enviamensaje_perfil_web/$', 'app.views.enviamensaje_perfil_web'),
    url(r'^listamensajes/(\d+)/(\d+)$', 'app.views.listamensajes'),
    url(r'^listamensajes/(\d+)$', 'app.views.listamensajes'),
    url(r'^busqueda/$', 'app.views.busqueda'),
    url(r'^actualizaperfil/$', 'app.views.actualizaperfil'),
    url(r'^filtrarcategoria/(\w+)/(\d+)/', 'app.views.filtrarcategoria'),
    url(r'^filtrarsubcategoria/(\w+)/(\d+)/', 'app.views.filtrarsubcategoria'),
    url(r'^traesubcategorias/(\d+)', 'app.views.traesubcategorias'),
    url(r'^uploadphoto/', 'app.views.uploadphoto'),
    url(r'^uploadvideo/', 'app.views.uploadvideo'),
    url(r'^categorias/', 'app.views.categorias'),
    url(r'^productocategoria/(\w+)/', 'app.views.productocategoria'),
    url(r'^busquedacategoria/(\w+)/(\w+)/', 'app.views.busquedacategoria'),
    url(r'^loginxfacebook/$', 'app.views.loginxfacebook'),
    url(r'^verificalogin/$', 'app.views.verificalogin'),
    url(r'^productosjson$', 'app.views.productosjson'),
    url(r'^productosjson/$', 'app.views.productosjson'),
    url(r'^detallechat/(\w+)/(\w+)/$', 'app.views.detallechat'),
    url(r'^detallechatpc/(\w+)/(\w+)/$', 'app.views.detallechatpc'),
    url(r'^detallechatpc/(\w+)/$', 'app.views.detallechatpc_1'),
    url(r'^prueba/$', 'app.views.prueba'),
    url(r'^noti/$', 'app.views.noti'),
    url(r'^detalleproducto/(\d+)', 'app.views.detalleproducto'),
    url(r'^eliminarphoto/(\d+)', 'app.views.eliminarphoto'),
    url(r'^addfavorito/(\d+)/(\d+)', 'app.views.addfavorito'),
    url(r'^estadofavorito/(\d+)', 'app.views.estadofavorito'),
    url(r'^misfavoritos/', 'app.views.misfavoritos'),
    url(r'^subirimgprofile/', 'app.views.subirimgprofile'),
    url(r'^recibenotis/', 'app.views.recibenotis'),
    url(r'^enviarnotis/(\d+)', 'app.views.enviarnotis'),
    url(r'^marcas/', 'app.views.marcas'),
    url(r'^modelos/(\d+)/', 'app.views.modelos'),
    url(r'^tipos/(\d+)/', 'app.views.tipos'),
    url(r'^colores/', 'app.views.colores'),
    url(r'^provincias/', 'app.views.provincias'),
    url(r'^distritos/(\d+)/', 'app.views.distritos'),
    url(r'^animales/', 'app.views.animales'),
    url(r'^empleos/', 'app.views.empleos'),
    url(r'^servicios/', 'app.views.servicios'),
    url(r'^cursos/', 'app.views.listcursos'),
    url(r'^mostrarcategorias/', 'app.views.mostrarcategorias'),
    url(r'^clasificados/', 'app.views.clasificados'),
    url(r'^favoritos/', 'app.views.favoritos'),
    url(r'^editarproducto/(\w+)/', 'app.views.editarproducto'),
    url(r'^eliminarproducto/(\w+)/', 'app.views.eliminarproducto'),
    url(r'^search/$', 'app.views.search', name='search'),
    url(r'^registro/$', 'app.views.registro', name='registro'),
    url(r'^registro$', 'app.views.registro', name='registro'),
    #url(r'^verficauser/(\w+)$', 'app.views.verficauser', name='verficauser'),


]